# Generated by Django 5.0.6 on 2024-05-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_user_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
