# Generated by Django 5.0.4 on 2024-05-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('kawaii', 'かわいい'), ('cool', 'かっこいい'), ('other', 'その他')], max_length=100),
        ),
    ]
