# Generated by Django 5.0.4 on 2024-05-22 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
