# Generated by Django 5.0.4 on 2024-05-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('kawaii', 'かわいい'), ('cool', 'かっこいい'), ('other', 'その他')], max_length=100, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル画像'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
